//! This is a platform-agnostic Rust driver for the TMP108 temperature sensor
//! based on the [`embedded-hal`] traits.
//!
//! [`embedded-hal`]: https://docs.rs/embedded-hal
//!
//! For further details of the device architecture and operation, please refer
//! to the official [`Datasheet`].
//!
//! [`Datasheet`]: https://www.ti.com/lit/gpn/tmp108

#![doc(html_root_url = "https://docs.rs/tmp108/latest")]
#![doc = include_str!("../README.md")]
#![cfg_attr(not(test), no_std)]

// Generated by `ddc build rust -s tmp108.ddsl -o src/inner.rs` (device-driver-cli).
// Do not edit by hand; regenerate from `tmp108.ddsl` instead.
#[allow(unused, unsafe_code, missing_docs)]
#[allow(clippy::all, clippy::pedantic)]
mod inner;

mod interface;

#[cfg(feature = "async")]
pub mod asynch;
pub mod blocking;

pub use crate::inner::{ConversionRate, Hysteresis, Mode, Polarity, Thermostat};

use crate::inner::Configuration;

/// A0 pin logic level representation.
#[derive(Debug, Default)]
pub enum A0 {
    /// A0 tied to GND (default).
    #[default]
    Gnd,
    /// A0 tied to V+.
    Vplus,
    /// A0 tied to SDA.
    Sda,
    /// A0 tied to SCL.
    Scl,
}

impl From<A0> for u8 {
    fn from(connection: A0) -> Self {
        match connection {
            A0::Gnd => 0b100_1000,
            A0::Vplus => 0b100_1001,
            A0::Sda => 0b100_1010,
            A0::Scl => 0b100_1011,
        }
    }
}

/// Tmp108 configuration parameters
#[derive(Clone, Copy, Debug, PartialEq)]
pub struct Config {
    /// Thermostat mode.
    pub thermostat_mode: Thermostat,
    /// Alert pin polarity.
    pub alert_polarity: Polarity,
    /// Conversion rate.
    pub conversion_rate: ConversionRate,
    /// Temperature hysteresis.
    pub hysteresis: Hysteresis,
}

impl Default for Config {
    fn default() -> Self {
        Self {
            thermostat_mode: Thermostat::Comparator,
            alert_polarity: Polarity::ActiveLow,
            conversion_rate: ConversionRate::OneHz,
            hysteresis: Hysteresis::OneC,
        }
    }
}

impl From<Configuration> for Config {
    fn from(c: Configuration) -> Self {
        Self {
            thermostat_mode: c.tm(),
            alert_polarity: c.pol(),
            conversion_rate: c.cr(),
            hysteresis: c.hys(),
        }
    }
}

impl Config {
    /// Write the modelled fields onto a configuration fieldset.
    ///
    /// Deliberately not a `From` impl: `Config` does not model the `m`, `fl`,
    /// `fh` and `id` fields, and `configure` uses `modify`, so those must be
    /// left untouched.
    pub(crate) fn apply(self, r: &mut Configuration) {
        r.set_tm(self.thermostat_mode);
        r.set_pol(self.alert_polarity);
        r.set_cr(self.conversion_rate);
        r.set_hys(self.hysteresis);
    }
}

impl ConversionRate {
    /// Time to wait for one conversion to complete, in microseconds.
    pub(crate) fn delay_us(self) -> u32 {
        match self {
            ConversionRate::QuarterHz => 4_000_000,
            ConversionRate::OneHz => 1_000_000,
            ConversionRate::FourHz => 250_000,
            ConversionRate::SixteenHz => 62_500,
        }
    }
}

const CELSIUS_PER_BIT: f32 = 0.0625;

pub(crate) fn to_celsius(t: i16) -> f32 {
    f32::from(t / 16) * CELSIUS_PER_BIT
}

#[allow(clippy::cast_possible_truncation)]
pub(crate) fn to_raw(t: f32) -> i16 {
    (t * 16.0 / CELSIUS_PER_BIT) as i16
}

/// Tmp108 Errors
#[derive(Debug)]
pub enum Error<E: embedded_hal::i2c::Error> {
    /// I2C Bus Error
    Bus(E),
    /// Invalid Input Error
    InvalidInput,
    /// Other Error
    Other,
}

#[cfg(feature = "embedded-sensors-hal")]
impl<E: embedded_hal::i2c::Error> embedded_sensors_hal::sensor::Error for Error<E> {
    fn kind(&self) -> embedded_sensors_hal::sensor::ErrorKind {
        embedded_sensors_hal::sensor::ErrorKind::Other
    }
}

#[cfg(test)]
mod tests {
    use super::inner::Configuration;
    use super::*;

    /// Power-on reset value of the configuration register, as declared in `tmp108.ddsl`.
    ///
    /// In device-driver v2 a fieldset's `Default` is all-zeroes; the reset value is
    /// applied by the register operation, so tests construct it explicitly.
    fn reset_configuration() -> Configuration {
        Configuration::from(0x1022u16.to_le_bytes())
    }

    #[test]
    fn config_round_trips_through_fieldset() {
        let config = Config {
            thermostat_mode: Thermostat::Interrupt,
            alert_polarity: Polarity::ActiveHigh,
            conversion_rate: ConversionRate::SixteenHz,
            hysteresis: Hysteresis::FourC,
        };

        let mut fieldset = reset_configuration();
        config.apply(&mut fieldset);

        assert_eq!(Config::from(fieldset), config);
    }

    #[test]
    fn apply_preserves_unmodelled_fields() {
        let mut fieldset = reset_configuration();
        fieldset.set_m(Mode::OneShot);
        fieldset.set_fl(true);
        fieldset.set_fh(true);
        fieldset.set_id(true);

        Config::default().apply(&mut fieldset);

        assert_eq!(fieldset.m().unwrap(), Mode::OneShot);
        assert!(fieldset.fl());
        assert!(fieldset.fh());
        assert!(fieldset.id());
    }

    #[test]
    fn conversion_rate_delays() {
        assert_eq!(ConversionRate::QuarterHz.delay_us(), 4_000_000);
        assert_eq!(ConversionRate::OneHz.delay_us(), 1_000_000);
        assert_eq!(ConversionRate::FourHz.delay_us(), 250_000);
        assert_eq!(ConversionRate::SixteenHz.delay_us(), 62_500);
    }

    #[test]
    fn celsius_conversions() {
        assert!((to_celsius(0x7ff0_u16.cast_signed()) - 127.9375).abs() < 1e-4);
        assert!((to_celsius(0) - 0.0).abs() < 1e-4);
        assert!((to_celsius(0xc900_u16.cast_signed()) + 55.0).abs() < 1e-4);
        assert_eq!(to_raw(127.9375), 0x7ff0_u16.cast_signed());
        assert_eq!(to_raw(-55.0), 0xc900_u16.cast_signed());
    }

    #[test]
    fn default_configuration() {
        let cfg = reset_configuration();
        assert_eq!(u16::from_le_bytes(cfg.into()), 0x1022);
    }

    #[test]
    fn modify_mode() {
        let mut cfg = reset_configuration();
        cfg.set_m(Mode::Shutdown);
        assert_eq!(u16::from_ne_bytes(cfg.into()), 0x1020);
        cfg.set_m(Mode::OneShot);
        assert_eq!(u16::from_ne_bytes(cfg.into()), 0x1021);
        cfg.set_m(Mode::Continuous);
        assert_eq!(u16::from_ne_bytes(cfg.into()), 0x1022);
    }

    #[test]
    fn modify_thermostat_mode() {
        let mut cfg = reset_configuration();
        cfg.set_tm(Thermostat::Comparator);
        assert_eq!(u16::from_ne_bytes(cfg.into()), 0x1022);
        cfg.set_tm(Thermostat::Interrupt);
        assert_eq!(u16::from_ne_bytes(cfg.into()), 0x1026);
    }

    #[test]
    fn modify_watchdog_temperature_flags() {
        let mut cfg = reset_configuration();
        cfg.set_fl(true);
        cfg.set_fh(false);
        assert_eq!(u16::from_ne_bytes(cfg.into()), 0x102a);
        cfg.set_fl(false);
        cfg.set_fh(true);
        assert_eq!(u16::from_ne_bytes(cfg.into()), 0x1032);
        cfg.set_fl(true);
        cfg.set_fh(true);
        assert_eq!(u16::from_ne_bytes(cfg.into()), 0x103a);
    }

    #[test]
    fn modify_conversion_rate() {
        let mut cfg = reset_configuration();
        cfg.set_cr(ConversionRate::QuarterHz);
        assert_eq!(u16::from_ne_bytes(cfg.into()), 0x1002);
        cfg.set_cr(ConversionRate::OneHz);
        assert_eq!(u16::from_ne_bytes(cfg.into()), 0x1022);
        cfg.set_cr(ConversionRate::FourHz);
        assert_eq!(u16::from_ne_bytes(cfg.into()), 0x1042);
        cfg.set_cr(ConversionRate::SixteenHz);
        assert_eq!(u16::from_ne_bytes(cfg.into()), 0x1062);
    }

    #[test]
    fn modify_hysteresis() {
        let mut cfg = reset_configuration();
        cfg.set_hys(Hysteresis::ZeroC);
        assert_eq!(u16::from_ne_bytes(cfg.into()), 0x0022);
        cfg.set_hys(Hysteresis::OneC);
        assert_eq!(u16::from_ne_bytes(cfg.into()), 0x1022);
        cfg.set_hys(Hysteresis::TwoC);
        assert_eq!(u16::from_ne_bytes(cfg.into()), 0x2022);
        cfg.set_hys(Hysteresis::FourC);
        assert_eq!(u16::from_ne_bytes(cfg.into()), 0x3022);
    }

    #[test]
    fn modify_polarity() {
        let mut cfg = reset_configuration();
        cfg.set_pol(Polarity::ActiveLow);
        assert_eq!(u16::from_ne_bytes(cfg.into()), 0x1022);
        cfg.set_pol(Polarity::ActiveHigh);
        assert_eq!(u16::from_ne_bytes(cfg.into()), 0x9022);
    }
}
